baseurl = "/"
languageCode = "zh_CN"
title = "Rongya Sun"
theme = "hugo-xmag"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true
canonifyurls = true
paginate = 6

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2


[params]
    description = "A website built through Hugo and blogdown."
    summary_length = 300
    footer = "&copy; [Rongya Sun](https://github.com/sunrongya/sunrongya.github.io) 2017 | [Github](https://github.com/sunrongya)"

[params.text]
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"
